word_to_id = {
    "<PAD>": 0,
    "<UNK>": 1,
    "the": 2,
    "of": 3,
    "in": 4,
    "image?": 5,
    "what": 6,
    "have": 7,
    "change": 8,
    "regions": 9,
    "areas": 10,
    "is": 11,
    "did": 12,
    "changed": 13,
    "non-vegetated": 14,
    "ground": 15,
    "surface": 16,
    "buildings": 17,
    "low": 18,
    "vegetation": 19,
    "trees": 20,
    "first": 21,
    "water": 22,
    "playgrounds": 23,
    "second": 24,
    "pre-change": 25,
    "pre-event": 26,
    "change?": 27,
    "image": 28,
    "mainly": 29,
    "to?": 30,
    "type": 31,
    "ratio": 32,
    "changed?": 33,
    "post-event": 34,
    "post-change": 35,
    "smallest": 36,
    "largest": 37,
    "increase?": 38,
    "decrease?": 39,
    "increased?": 40,
    "decreased?": 41,
    "percentage": 42,
    "how": 43,
    "much": 44,
    "area": 45,
    "has": 46,
    "proportion": 47,
    "areas?": 48,
    "non-change": 49,
    "imagery?": 50,
    "regions?": 51,
    "largest?": 52,
    "smallest?": 53,
    "unchanged": 54,
    "not": 55
}


id_to_word = {
    idx: word
    for word, idx in word_to_id.items()
}